# Site settings
name: echidna
# description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
baseurl: "/echidna" # the subpath of your site, e.g. /blog/
#url: "http://ashleyrback.github.io/echidna" # the base hostname & protocol for #your site
twitter_username: 
github_username:  ashleyrback

# Build settings
markdown: kramdown

kramdown:
  input: GFM